---
title: "Model Building and Model Selection/Fitting"
author: "Leslie Mei"
date: "January 14, 2019"
output: github_document
---

## Building models

### Deviant aggressive behavior
>\ 1\. What social policy would be appropriate to reduce deviant aggressive behavior if Theory I were correct?

If we assume that individuals learn deviant aggressive behavior from experience, in that they behave as they are conditioned to do so through a system of reward and punishment, then aggressive behavior must be punished more stringently and socially cooperative behavior must be rewarded more consistently, in a socially enforceable way. For example, young children are given a time-out when they hit their classmates, whereas they receive stickers or treats for good behavior. Unforeseen rewards for aggressive behavior (not awarded by the system) that might balance out the punishments must also be mitigated as much as possible. With young children, it might be that aggressive behavior allows them to intimidate their classmates into giving up their share of treats. Teachers try to mitigate this by confiscating stolen goods, or returning them to their proper owners.

>  Theory II?

If we assume that individuals exhibit deviant aggressive behavior as a symbolic expression of hostility that results from personal frustrations, they must learn how to more adequately deal with these frustrations. Their bond with authority figures must also be strengthened through the building of trust and empathy. This is best achieved through cognitive behavioral therapy, or other forms of psychotherapy like medication and institutionalization. For example, individuals accused of a violent crime but determined unfit to stand trial are institutionalized, sometimes for the rest of their lives, because their frustration could not successfully be eliminated - therefore, they must be contained.

>  Theory III?

If we assume that individuals exhibit deviant aggressive behavior as the rational action of their oppressed status, then the conditions of their oppressed status must be ameliorated so that they have opportunities and resources equal to their majority counterparts. Social policies must target the discrepancies in their situations rather than the aggressive behavior itself; as the inequalities are adjusted, the aggressive behavior will naturally decrease. For example, Black and Latino Americans are disproportionately jailed due to the crackdown on marijuana. Though dealing in drugs is not inherently violent, the minority status of the individuals who do so make them targets of a system which disproportionately values White Americans over non-White Americans. That is to say, their actions may be rational even though they are not lawful.

>  Theory IV?

If we assume that individuals become socialized in deviant aggressive behavior through contact with a deviant subculture, then the subculture must be stigmatized as much as possible, and its members excluded from mainstream society in the form of job opportunities, customer service, and social contact. Legally, the subculture or certain practices might also be made punishable so as to further discourage people from engaging in the associated behaviors. For example, neo-Nazis are stigmatized and shunned by most of mainstream society, even if they have not yet displayed outward violence. This is a preventative measure against being socialized through contact with their deviant aggressive behavior.

>\ 2\. During the past ten years, American society has been running a series of “experiments” with deviant aggressive behavior. Take any one of these experiments (e.g. #MeToo, mass shootings, political rhetoric) and discuss what we have learned about the four theories from this series of experiments.

The way in which society has dealt with fascists, neo-Nazis, and the alt-right has been an interesting case study in how deviant aggressive behavior is treated, particularly because there is disagreement on whether their ideologies are truly deviant or aggressive.

Many liberally minded people treat the alt-right's deviant aggressive behavior as learned behavior (Theory I), and enact proportionate punishment by ridiculing them, excluding them, and occasionally using reciprocal violence. The stigmatism of fascism has become so evident that words like 'fascist' and 'Nazi' are themselves taboo, and eschewed by the ultra-conservatives who nevertheless subscribe to the same ideals. In this way, the general public avoids contact with their subculture (Theory IV). Those who renounce their neo-Nazi backgrounds are also rewarded by positive media coverage as well as a positive general public opinion.

Some people have tried to explain the rise of the alt-right as the reaction of maladjusted young men to a society which increasingly seems to have less room for them; that is, they take their radicalization to be a symbolic expression of hostility towards authority (Theory II). Many of the members themselves subscribe to the belief that they are an oppressed minority taking back what is rightfully theirs, in spite of already holding the majority of power and resources in the country (Theory III).

From this case study, we can see that Theory I and IV are less forgiving and focus on reduction of harm to those outside the community, whereas Theory II and III try to lend more nuance to the reasoning behind the behavior and focus on the pain of those inside the community. This is perhaps comparable to the difference between prediction and inference - caring about the input and output vs caring about the exact thought processes and how to interpret them.

### Waiting until the last minute
> People often do things at the last minute (students turning in papers, professors grading exams, and so on).

>\ a\. Ask yourself why the observation might be true and write down your explanations.

People often procrastinate because they are paralyzed by stress. Distracting oneself from the task at hand provides a temporary relief from the stress of completing the task, which negatively reinforces more of this behavior. Repeat this enough times and only the overwhelming stress of being close to the deadline provides enough impetus to finally complete the task.

>\ b\. Generalize the explanatory model – that is, induce the most general, abstract model you can produce that still has the original observation as a consequence.

Stress causes people to avoid tasks they might otherwise enjoy or be equipped to handle.

>\ c\. Induce an alternative model that also has the original observation as a consequence.

People do not necessarily *do* things at the last minute, they simply turn things in close to the deadline. Most people would rather have more time to work on something than less, and since we seldom track when people begin their assignments, someone who began their assignment immediately and worked on it methodically over two weeks would look the same as someone who began it the night before as long as they turned it in at the same time. Even within the people who 'do things at the last minute,' we will have variation between turning things in two minutes before deadline and one day before deadline.

>\ d\. For each of the two general models produced in (b) and (c), derive two interesting predictions (four predictions in total). Be sure the logical connection between your model and your predictions is explicitly stated and that any assumed facts concerning the world are made explicit.

**Predictions for *b***

1. Stress impacts performance in something like a quadratic curve - people are likely to complete a task when there is zero stress attached (aka hobbies and passion projects) and when there is overhwelming stress attached (aka the matter is urgent).
2. Helping people practice relaxation techniques will mitigate their stress and thereby lessen the degree of procrastination.

**Predictions for *c***

1. If we were to track the amount of time people spend on an assignment and the time at which they turned it in, the two would be more or less uncorrelated.
2. Those who spend more time on an assignment (and therefore procrastinated less) would report less stress than those who spend less time on an assignment (and therefore procrastinated more).

## Selecting and fitting a model